export const antdTheme = {
  token: {
    colorPrimary: '#C4A36A',
    colorInfo: '#C4A36A',
    colorSuccess: '#8A9A6B',
    colorText: '#3A322B',
    colorTextHeading: '#1B2431',
    colorBgContainer: 'transparent',
    colorBgElevated: '#F6F0E6',
    colorBorder: '#C4A36A',
    colorBorderSecondary: 'rgba(196, 163, 106, 0.35)',
    borderRadius: 0,
    borderRadiusLG: 0,
    fontFamily: "'Outfit', system-ui, sans-serif",
    fontSize: 15,
    controlHeight: 40,
    controlOutline: 'transparent',
    boxShadow: 'none',
    boxShadowSecondary: 'none',
    wireframe: true,
    motionDurationMid: '0.28s',
  },
  components: {
    Modal: {
      contentBg: '#F7F1E6',
      headerBg: 'transparent',
      titleFontSize: 0,
      paddingMD: 0,
      paddingContentHorizontalLG: 0,
      paddingContentVerticalLG: 0,
    },
    Drawer: {
      colorBgElevated: '#F4EDE0',
      paddingLG: 0,
    },
    Input: {
      activeShadow: 'none',
      hoverBorderColor: '#C4A36A',
      activeBorderColor: '#C4A36A',
      colorBgContainer: 'transparent',
      paddingBlock: 10,
    },
    Select: {
      optionSelectedBg: 'rgba(196, 163, 106, 0.16)',
      optionActiveBg: 'rgba(196, 163, 106, 0.1)',
      colorBgElevated: '#F7F1E6',
      controlOutline: 'transparent',
    },
    Collapse: {
      headerBg: 'transparent',
      contentBg: 'transparent',
      headerPadding: '18px 0',
      contentPadding: '0 0 16px 0',
    },
    Form: {
      itemMarginBottom: 16,
      labelColor: '#A4844A',
      labelFontSize: 11,
    },
    Carousel: {
      dotWidth: 18,
      dotHeight: 2,
      dotActiveWidth: 32,
    },
  },
};
